services:
  portfolio-ssh:
    image: portfolio-ssh:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 1GB
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "22:22"
    stdin_open: true
    tty: true
    secrets:
      - source: host_key
        target: /run/secret/authorized_keys/id_ed25519
secrets:
  host_key:
    file: ./authorized_keys/id_ed25519
